# Generated by Django 2.2.12 on 2020-09-06 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=255)),
                ('datum', models.DateField()),
                ('opis', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'testi',
                'ordering': ['datum', 'naslov'],
            },
        ),
        migrations.CreateModel(
            name='Naloga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generator', models.CharField(choices=[('VstaviUstreznoOblikoGenerator', 'Vstavi ustrezno obliko iztočnice'), ('NajdiVsiljivcaSpol', 'Najdi vsiljivca glede na spol'), ('NajdiVsiljivcaBesednaVrsta', 'Najdi vsiljivca glede na besedno vrsto')], max_length=60)),
                ('navodila', models.TextField(blank=True)),
                ('stevilo_primerov', models.PositiveSmallIntegerField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='naloge', to='naloge.Test')),
            ],
            options={
                'verbose_name_plural': 'naloge',
                'default_related_name': 'naloge',
            },
        ),
    ]
