# Generated by Django 3.1.1 on 2020-09-08 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naloge', '0002_auto_20200907_1156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['naslov'], 'verbose_name_plural': 'testi'},
        ),
        migrations.RemoveField(
            model_name='test',
            name='datum',
        ),
    ]
