# Generated by Django 2.2.12 on 2020-04-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naloge', '0002_auto_20200215_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='naloga',
            old_name='zahtevnost',
            new_name='stevilo_primerov',
        ),
        migrations.AlterField(
            model_name='naloga',
            name='generator',
            field=models.CharField(choices=[('VstaviUstreznoOblikoGenerator', 'Vstavi ustrezno obliko iztočnice')], max_length=60),
        ),
    ]
