# Generated by Django 2.2.12 on 2020-04-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naloge', '0003_auto_20200426_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='naloga',
            name='navodila',
            field=models.TextField(blank=True),
        ),
    ]
